Task2 solution
TalgatMIPT/AndroidCourse pull request #1
Opened 2019-10-02 21:16 UTC by TalgatMIPT

2019-10-09 22:11 UTC, IvanShafran requested changes
Жду правок

2019-10-09 22:11 UTC, IvanShafran commented on LayoutCreatingTask2/app/src/main/java/com/talgat/layoutcreatingtask2/MainActivity.java
> +        this.setTitle("Notes");
Хардкод строк, которые видны пользователям, обязательно выносить в ресурсы

2019-10-09 22:11 UTC, IvanShafran commented on LayoutCreatingTask2/app/src/main/java/com/talgat/layoutcreatingtask2/MainActivity.java
> +        emailButton.setBackgroundColor(Color.parseColor("#009688"));
Такие штуки обычно в XML разметке указывают.
В этой статье про это хорошо описано: https://code.luasoftware.com/tutorials/android/change-android-button-color-while-maintain-effect-and-state-color/

2019-10-09 22:11 UTC, IvanShafran commented on LayoutCreatingTask2/app/src/main/java/com/talgat/layoutcreatingtask2/MainActivity.java
> +                emailIntent.putExtra(Intent.EXTRA_SUBJECT, "Notes feedback");
Эти штуки тоже видны пользователю в итоге, поэтому стоит вынести в ресурсы

2019-10-09 22:11 UTC, IvanShafran commented on LayoutCreatingTask2/app/src/main/res/layout/activity_main.xml
> +    <RelativeLayout
1) Хорошо, что познакомился с RelativeLayout.
Но тут проще использовать LinearLayout с orientation="vertical"
2) Внешний ConstraintLayout не используется бесполезен, т.к. внутри него одна View всего.
Поэтому удали, пожалуйста, ConstraintLayout и сделай LinearLayout корнем. (не забудь оставить xlmns namespace-ы)

2019-10-09 22:11 UTC, IvanShafran commented on LayoutCreatingTask2/app/src/main/res/layout/activity_main.xml
> +            android:layout_marginLeft="16dp"
Не критично, но рекомендуется использовать start вместо left и end вместо right. Это важно для rtl языков.
На текущий момент приложение не поддерживает right to left языки. Но если понадобится, то большая часть разметки уже будет готова.

2019-10-23 20:58 UTC, TalgatMIPT commented on LayoutCreatingTask2/app/src/main/java/com/talgat/layoutcreatingtask2/MainActivity.java
> +        emailButton.setBackgroundColor(Color.parseColor("#009688"));
Исправил

2019-10-23 20:58 UTC, TalgatMIPT commented on LayoutCreatingTask2/app/src/main/java/com/talgat/layoutcreatingtask2/MainActivity.java
> +        this.setTitle("Notes");
Исправил

2019-10-23 20:59 UTC, TalgatMIPT commented on LayoutCreatingTask2/app/src/main/java/com/talgat/layoutcreatingtask2/MainActivity.java
> +                emailIntent.putExtra(Intent.EXTRA_SUBJECT, "Notes feedback");
Исправил

2019-10-23 20:59 UTC, TalgatMIPT commented on LayoutCreatingTask2/app/src/main/res/layout/activity_main.xml
> +    <RelativeLayout
Переделал

2019-10-23 20:59 UTC, TalgatMIPT commented on LayoutCreatingTask2/app/src/main/res/layout/activity_main.xml
> +            android:layout_marginLeft="16dp"
Исправил во всех местах

2019-10-23 21:21 UTC, IvanShafran approved these changes

2019-10-23 21:21 UTC, IvanShafran commented on LayoutCreatingTask2/app/src/main/res/layout/activity_main.xml
> +    <RelativeLayout
Тут всё ещё есть лишняя вложенность. Но я придираться больше не буду к этому, т.к. в следующем ДЗ верстка тут всё равно изменится

2019-10-23 21:21 UTC, merged

2019-10-23 21:22 UTC, IvanShafran commented
Отличная работа 👍 Жду следующих ДЗ)