project was renamed and task3 solution inc
TalgatMIPT/AndroidCourse pull request #2
Opened 2019-11-10 18:10 UTC by TalgatMIPT

2019-11-11 12:51 UTC, IvanShafran requested changes
Отличная работа) Посмотри, пожалуйста, замечания

2019-11-11 12:51 UTC, IvanShafran commented on AnsroidCourseProject/app/build.gradle
> +        minSdkVersion 19
Можно и с 21-го, но если хочешь с 19, то тоже ОК

2019-11-11 12:51 UTC, IvanShafran commented on AnsroidCourseProject/app/build.gradle
> +    }/*
Закомментированный код -- обычно плохой знак.
Если хочешь, то использовать 1.8 compatibility можно
Если не нужно, то удали, пожалуйста

2019-11-11 12:51 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/MainActivity.java
> +        recyclerView.getRecycledViewPool().setMaxRecycledViews(0, 15);
15 -- это перебор на самом деле. Для списка в один столбец будет хватать: 2 или 3. Для списка в два стоблца, как в следующих дз -- 4 - 5.
Проверить это можно так:
1. в onCreateViewHolder добавляешь Log.d -- типа создался ViewHolder
2. Запускаешь и фигачишь список вверхи и вниз
3. Если логи о создании постоянно сыпяться, то надо увеличить число, иначе можно попробовать уменьшить
И надо найти эту границу, когда логи не сыпяться постоянно, но если уменьшить на один, то будут

2019-11-11 12:51 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/MainActivity.java
> +        NotesHandler.create(this);
В App уже вижу, что вызван метод был уже

2019-11-11 12:51 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/Note.java
> +    Note(int id, Date date, String text, String title, long drawableIdRes) {
drawableIdRes кажется не может быть long, а только int
А вот id лучше сделать long -- когда будет дз с базой данных, то это пригодится

2019-11-11 12:51 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/NotesHandler.java
> +public final class NotesHandler {
Мне не очень нравится название:
1. В Android есть класс Handler и он ассоциируется с этим
2. Handler -- обработчик. В нашем случае это скорее абстракция над данными

Мои предложения:
NotesRepository
NotesDataSource
NotesStorage
- или любое другое, но более близкое к абстракции над данными

2019-11-11 12:51 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/NotesViewHandler.java
> +    private TextView noteTitleView;
Можно даже final пометить все поля, но это необязательно

2019-11-11 12:51 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/res/layout/activity_main.xml
> +<!--
Закомментированный код надо убрать

2019-11-11 12:51 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/res/layout/note_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
LinearLayout лишний здесь

2019-11-13 15:48 UTC, TalgatMIPT commented on AnsroidCourseProject/app/build.gradle
> +    }/*
Сори, забыл исправить

2019-11-13 15:49 UTC, TalgatMIPT commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/MainActivity.java
> +        recyclerView.getRecycledViewPool().setMaxRecycledViews(0, 15);
Спасибо, учел

2019-11-13 15:49 UTC, TalgatMIPT commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/MainActivity.java
> +        NotesHandler.create(this);
Да, убрал из активити вызов

2019-11-13 15:49 UTC, TalgatMIPT commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/NotesHandler.java
> +public final class NotesHandler {
Исправил

2019-11-13 15:50 UTC, TalgatMIPT commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/NotesViewHandler.java
> +    private TextView noteTitleView;
Добавил

2019-11-13 15:50 UTC, TalgatMIPT commented on AnsroidCourseProject/app/src/main/res/layout/note_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Кажется, не лишний. Пробовал без него - ругается. Да и у тебя в примере, кажется, он есть

2019-11-13 16:12 UTC, IvanShafran requested changes
Убери, пжлста, LinearLayout внешний всё-таки. С ним approve совесть не даст поставить

2019-11-13 16:12 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/res/layout/note_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
LinearLayout может быть полезен, если внутри есть хотя бы два View(прямых ребенка).
Внутри этого только одно дочернее)
Ругается, потому что namespace объявлен в нём, думаю.
Скопируй сначала в CardView, а потом удали:
xmlns:android="http://schemas.android.com/apk/res/android"

Должно заработать

2019-11-13 16:12 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/Note.java
> +    Note(int id, Date date, String text, String title, int drawableIdRes) {
id всё ещё int :( Надо long id

2019-11-18 13:35 UTC, TalgatMIPT commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/Note.java
> +    Note(int id, Date date, String text, String title, int drawableIdRes) {
Сори, поправил

2019-11-18 13:37 UTC, TalgatMIPT commented on AnsroidCourseProject/app/src/main/res/layout/note_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Попробовал, при удалении все равно жалуется, пришлось оставить ссылку на стили в карточке, но зато уже без LenearLayout :)

2019-11-18 13:47 UTC, IvanShafran approved these changes
Супер 👍 
Давай догоняй остальные домашки

2019-11-18 13:47 UTC, merged

2019-11-18 14:03 UTC, IvanShafran commented
4 и 5 дз можно в одном PR отправить. 4 дз очень простое