Task45 solution
TalgatMIPT/AndroidCourse pull request #3
Opened 2019-12-03 12:25 UTC by TalgatMIPT

2019-12-07 21:30 UTC, IvanShafran requested changes

2019-12-07 21:30 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/ListFragment.java
> +        if (shouldSetTwoSpan())
Я больше предпочитаю всегда добавлять {}, чтобы случайно не ошибиться. Знаю, что многие на это тригерятся также. Поэтому лучше {} использовать :)

2019-12-07 21:30 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/res/layout-sw600dp/activity_main.xml
> +<?xml version="1.0" encoding="utf-8"?>
Этот файл можно удалить. Достаточно layout и layout-sw600dp-land. layout папка будет применяться для всех случаев кроме большого экрана в landscape

2019-12-07 21:30 UTC, IvanShafran commented on AnsroidCourseProject/app/src/main/res/layout-land/activity_main.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Можно удалить тоже

2019-12-09 11:08 UTC, TalgatMIPT commented on AnsroidCourseProject/app/src/main/java/com/talgat/layoutcreatingtask2/ListFragment.java
> +        if (shouldSetTwoSpan())
У меня на работе просто со скобками немного другая политика, поэтому так писал (если отсутствие улучшает читаемость - можно убрать). Исправил

2019-12-09 11:09 UTC, TalgatMIPT commented on AnsroidCourseProject/app/src/main/res/layout-sw600dp/activity_main.xml
> +<?xml version="1.0" encoding="utf-8"?>
Удалил

2019-12-09 11:09 UTC, TalgatMIPT commented on AnsroidCourseProject/app/src/main/res/layout-land/activity_main.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Удалил

2019-12-09 12:13 UTC, merged